/*
 * Filename: swc_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component control which sets the speed signal value
 * name: swc_control
 * shortname: control
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_control.h"

#include "stdio.h"
#include "stdlib.h"

/* USER CODE START SWC_CONTROL_INCLUDE */

/* USER CODE END SWC_CONTROL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_CONTROL_USERDEFINITIONS */

/* USER CODE END SWC_CONTROL_USERDEFINITIONS */



/*
 * component: swc_control
 * cycletime: 0
 * description: Runnable that checks the joystick signal and depending upon that value speed signal is updated
 * events: ev_on_JoystickUpdate
 * name: CONTROL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void CONTROL_calcControl_run(RTE_event ev){
	
	/* USER CODE START CONTROL_calcControl_run */   
    sint8_t JoyStick_X_value = 0;

    SC_SPEED_data_t Speed_Signal_Data = SC_SPEED_INIT_DATA;
    
    //Get the Joystick data from the SWC joystick
    if(RTE_SC_JOYSTICK_getStatus(&SO_JOYSTICK_signal) == RTE_SIGNALSTATUS_VALID)
    {
        JoyStick_X_value = RTE_SC_JOYSTICK_get(&SO_JOYSTICK_signal).x;
    }
    
    //Set the X value of the joystick to the speed data based on the condition given.
    if(JoyStick_X_value > 0)
    {
        Speed_Signal_Data.speed_value = 2 * (JoyStick_X_value);
    }
    else if(JoyStick_X_value <= 0)
    {
        Speed_Signal_Data.speed_value = 0;
    }
    
    //pass the value of speed signal to the next required runnables.
    RTE_SC_SPEED_set(&SO_SPEED_signal, Speed_Signal_Data);
    
    WD_Alive(run_calcControl_pos); 
    
    /* USER CODE END CONTROL_calcControl_run */
}

/* USER CODE START SWC_CONTROL_FUNCTIONS */

/* USER CODE END SWC_CONTROL_FUNCTIONS */

