/*
 * Filename: swc_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component brakelight which updates it's runnable based on the speed signal value.
 * name: swc_brakelight
 * shortname: brakelight
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight.h"



/* USER CODE START SWC_BRAKELIGHT_INCLUDE */

/* USER CODE END SWC_BRAKELIGHT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */



/*
 * component: swc_brakelight
 * cycletime: 0
 * description: Runnable that is updated on speed signal value change.
 * events: ev_on_SpeedUpdate
 * name: BRAKELIGHT_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_speed
 * signalOUT: so_brakelight
 * task: tsk_io
 */
void BRAKELIGHT_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START BRAKELIGHT_setBrakeLight_run */   
    
    SC_SPEED_data_t Speed_Signal_Data = SC_SPEED_INIT_DATA;
    
    //Here we need to get the speed signal value which is calcControl runnable.
    if(RTE_SC_SPEED_getStatus(&SO_SPEED_signal) == RTE_SIGNALSTATUS_VALID)
    {
        Speed_Signal_Data = RTE_SC_SPEED_get(&SO_SPEED_signal);
    }
    
    SC_BRAKELIGHT_data_t BrakeLight_Signal_Data = SC_BRAKELIGHT_INIT_DATA;
    
    if(Speed_Signal_Data.speed_value == 0)
    {
        BrakeLight_Signal_Data.brakelight_value = TRUE;
    }
    else
    {
        BrakeLight_Signal_Data.brakelight_value = FALSE;
    }
    
    RTE_SC_BRAKELIGHT_set(&SO_BRAKELIGHT_signal, BrakeLight_Signal_Data);
    
    WD_Alive(run_brakelight_pos);
        
    //The BrakeLight value is sent out through pushPort API.
    RTE_SC_BRAKELIGHT_pushPort(&SO_BRAKELIGHT_signal);
    
    /* USER CODE END BRAKELIGHT_setBrakeLight_run */
}

/* USER CODE START SWC_BRAKELIGHT_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_FUNCTIONS */

