/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Software component contains runnable for the engine
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"



/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable that copies the speed signal value to the engine signal value and calls the driver pushport().
 * events: 
 * name: ENGINE_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: so_engine
 * task: tsk_io
 */
void ENGINE_setEngine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_setEngine_run */   
        
    SC_SPEED_data_t Speed_Signal_Data = SC_SPEED_INIT_DATA;
    
    static uint32_t Speed_Signal_Age = 0;
    
    SC_ENGINE_data_t Engine_Signal_Data = SC_ENGINE_INIT_DATA;
    
    //Here we need to get the speed signal value which is calcControl runnable.
    if(RTE_SC_SPEED_getStatus(&SO_SPEED_signal) == RTE_SIGNALSTATUS_VALID)
    {
        Speed_Signal_Data.speed_value = RTE_SC_SPEED_get(&SO_SPEED_signal).speed_value;
    }
    
    //getAge function returns the age of the signal. Here for example Max of 500m sec will be checked for the signal age.
    Speed_Signal_Age = RTE_SC_SPEED_getAge(&SO_SPEED_signal);
    
    if(Speed_Signal_Age < 500)
    {
        Engine_Signal_Data.engine_value = Speed_Signal_Data.speed_value;
    }
    else
    {
        Engine_Signal_Data.engine_value = 0;
        //UART_LOG_PutString("Too old speed signal data");  //Debug statement
    }
    
    // We set the new value of engine data copied from speed signal to engine signal
    RTE_SC_ENGINE_set(&SO_ENGINE_signal, Engine_Signal_Data);
        
    WD_Alive(run_engine_pos); 
        
    //The engine value is sent out through pushPort API.
    RTE_SC_ENGINE_pushPort(&SO_ENGINE_signal); // Error handle the pushport.
    
    /* USER CODE END ENGINE_setEngine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

